version: "3.9"
services:
  web:
    container_name: hackernews-clone
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/wait-for-it.sh:/tmp/wait-for-it.sh
    depends_on:
      - "mysql-server"
    command: /bin/bash -c "chmod +x /tmp/wait-for-it.sh && /tmp/wait-for-it.sh mysql-server:3306 -- /app/main"

  mysql-server:
    image: mysql
    container_name: hackernews-clone-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: hackernews_clone_user
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: hackernews_clone
    ports:
      - "3306:3306"